name: Build Shikinha

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Build image
      run: podman build -t shikinha:latest .
