name: Build and Deploy Shikinha

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image with Podman
      run: podman build -t shikinha:latest .

    - name: Run container
      run: podman run -d --replace --name Shikinha shikinha:latest
      
